### ISSUE TITLE
请不要将 openapi-util 锁定在 JDK8 版本

### ISSUE THREAD

**Issue by laohyx** [aliyun/darabonba-openapi-util#95]
问题描述：
5天以前的commit (发布的 0.1.10) 再次加入了 JDK7/8 的类（目的应该是支持 JDK7）？
https://github.com/aliyun/darabonba-openapi-util/commit/02e4f1514c2204694d8de805b0fa912f75a09f7d

打包部署后，在我们的应用中出现了下列错误：
```
java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at com.aliyun.openapiutil.Client.getRPCSignature(Client.java:374) ~[openapiutil-0.1.10.jar!/:na]
	at com.aliyun.teaopenapi.Client.doRPCRequest(Client.java:154) ~[tea-openapi-0.0.7.jar!/:na]
	at com.aliyun.dysmsapi20170525.Client.sendSmsWithOptions(Client.java:238) ~[dysmsapi20170525-2.0.1.jar!/:na]
	at com.aliyun.dysmsapi20170525.Client.sendSms(Client.java:243) ~[dysmsapi20170525-2.0.1.jar!/:na]
```

原因是我们的运行环境是JDK11，没有 `sum.misc.BASE64Encoder`.

原因请参考这个链接。
https://stackoverflow.com/questions/29692146/java-lang-noclassdeffounderror-sun-misc-base64encoder

但作为阿里云短信SDK的一部分（com.aliyun:dysmsapi20170525, 版本 2.0.1），应该达到尽量多版本的支持。

上一周我们的打包的应用，还在使用 openapiutil:0.1.9，本周打包的依赖就变成0.1.10了。然而我们的运行环境是 JDK 11。

![image](https://user-images.githubusercontent.com/1221508/125573832-ae790b35-7018-47b2-9f29-82ecc9a13f85.png)

我相信有大量的开发者使用阿里云短信SDK，但使用Java 11以上的运行环境。

所以考虑到SDK的适用性，请尽可能使用 java.util.Base64, 而非 sun.misc.BASE64Encoder

谢谢

**Comment by yndu13** [comment]
考虑到JDK7以下用户，我们不能选择使用java.util.Base64，不过我们后面做了相关修改，您依赖最新版试试

**Comment by laohyx** [comment]
好的，谢谢！
